# Generated by Django 4.1.5 on 2023-01-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='password',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
