# Generated by Django 4.1.5 on 2023-01-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_user_master_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
